#!/usr/bin/env bash
# Configures Nginx to serve a 'Hello World!' page at the root on port 80.

sudo apt-get update -y
sudo apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx restart
