#!/usr/bin/env bash
# Configures a brand new Ubuntu machine with Nginx to redirect /redirect_me to another page with a 301 Moved Permanently status.

if [ "$(id -u)" != "0" ]; then
	   echo "This script must be run as root" 1>&2
	      exit 1
fi

apt-get update -y
apt-get install nginx -y

ufw allow 'Nginx HTTP'

file="/etc/nginx/sites-available/default"

redirect_string='location \/redirect_me { return 301 https:\/\/www.newsite.com; }'

sed -i "/server_name _;/a $redirect_string" $file

service nginx reload
