#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page with "Ceci n'est pas une page"

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

apt-get update -y
apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Ceci n'est pas une page" > /var/www/html/404.html

cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.newsite.com;
    }

    error_page 404 /404.html;
    
    location = /404.html {
        internal;
    }
}
EOF

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

nginx -t && service nginx restart
