#!/usr/bin/env bash
# Install and configure HAproxy

apt-get -y update
apt-get install -y haproxy

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
	mode http
	timeout client 15s
	timeout connect 10s
	timeout server 15s
	timeout http-request 10s

frontend am-trustdev.tech-frontend
	bind *:80
	default_backend am-trustdev.tech-backend

backend am-trustdev.tech-backend
	balance roundrobin
	server 512139-web-01 54.174.153.120:80 check
	server 512139-web-02 18.204.14.78:80 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
