#!/usr/bin/env bash
# Script that installs and configures HAproxy.

# Install HAproxy on
apt-get -y update
apt-get -y install haproxy=2.6.\*

# Configure haproxy
echo '
frontend am-trustdev.tech
	bind *:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 512139-web-01 54.174.153.120:80 check
	server 512139-web-02 18.204.14.78:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
