#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

if [ "$(id -u)" != "0" ]; then
	    echo "This script must be run as root" 1>&2
	        exit 1
fi

apt-get update -y
apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get update -y
apt-get install -y haproxy=2.6.*

HA_CFG="/etc/haproxy/haproxy.cfg"
FRONT_EXISTS=$(grep -c "frontend http_front" "$HA_CFG")
BACK_EXISTS=$(grep -c "backend http_back" "$HA_CFG")

if [ "$FRONT_EXISTS" -eq 0 ] && [ "$BACK_EXISTS" -eq 0 ]; then
	    cat <<EOF >> "$HA_CFG"

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 512139-web-01 54.174.153.120:80 check
    server 512139-web-02 18.204.14.78:80 check
EOF
else
    echo "Frontend or Backend configuration already exists. Please review $HA_CFG."
fi

# Restart HAProxy to apply the new configuration
systemctl restart haproxy
systemctl enable haproxy
