#!/usr/bin/env bash
# This is Bash script that displays the content of the file /etc/passwd, using the while loop + IFS in a specific FORMAT.

file=/etc/passwd

while read -r line
do
	IFS=: read -r -a fields <<< "$line"

	username=${fields[0]}
	password=${fields[1]}
	id=${fields[2]}
	group_id=${fields[3]}
	user_id_info=${fields[4]}
	home_directory=${fields[5]}
	command_shell=${fields[6]}

	format="The user $username is part of the $group_id gang, lives in $home_directory and rides $command_shell. $id's place is protected by the passcode $password, more info about the user here: $user_id_info"

	echo "$format"

done < "$file"
