#!/usr/bin/env bash
# This is a Bash script that groups visitors by IP and HTTP status code, and displays this data.
# The output is ordered from the greatest to the lowest number of occurrences.

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
