#!/usr/bin/env bash
# This is a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
while [ "$hour" -le 12 ]; do
	case "$hour" in
		0)
			echo "Hour: $hour"
			;;
		1)
			echo "Hour: $hour"
			;;
		2)
			echo "Hour: $hour"
			;;
		3)
			echo "Hour: $hour"
			;;
		4)
			echo "Hour: $hour"
			;;
		5)
			echo "Hour: $hour"
			;;
		6)
			echo "Hour: $hour"
			;;
		7)
			echo "Hour: $hour"
			;;
		8)
			echo "Hour: $hour"
			;;
		9)
			echo "Hour: $hour"
			;;
		10)
			echo "Hour: $hour"
			;;
		11)
			echo "Hour: $hour"
			;;
		12)
			echo "Hour: $hour"
			;;
	esac

	minute=1
	while [ "$minute" -lt 60 ]; do
		echo "$minute"
		((minute++))
	done

	((hour++))
done
