#!/usr/bin/env bash
# This Bash script checks if: 
# 1- the file school exists or not
# 2- the file school is empty or not
# 3- the file school is a regular file

path="$(pwd)"/school
if [ -e "$path" ]; then
	echo "school file exists"
	if [ -s "$path" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$path" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
