#!/usr/bin/env bash
# Script to configure Docker container to serve "Hello Holberton" via Apache
apt-get update
apt-get install apache2 -y
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
service apache2 reload
